import type {
  DigestStats,
  EvidenceItem,
  OrderVault,
  SourceMessage,
  TimelineEvent,
} from './types'

export const MERCHANT = {
  name: 'East London Camera Store',
  mailbox: 'support@eastlondoncamera.example',
  platform: 'Shopify + Stripe',
}

// ── Order #1048 — full 7-email mailbox sequence ─────────────────────────────
export const SEED_MAILBOX: SourceMessage[] = [
  {
    id: 'm1',
    platform: 'Shopify',
    from: 'orders@shopify.com',
    to: MERCHANT.mailbox,
    subject: 'New order #1048 — Refurbished camera lens',
    body: `You received your order. Order #1048 has been placed by Daniel Okafor.
Thank you for purchasing. Product: Refurbished 50mm camera lens. Amount: £420.00 GBP.
Ship to: 14 Mare Street, London, E8 3QE. Customer email: daniel.okafor@example.com.
Refund policy: 30-day returns, buyer covers return shipping.`,
    receivedAt: '2026-06-10T10:14:00Z',
  },
  {
    id: 'm2',
    platform: 'Stripe',
    from: 'receipts@stripe.com',
    to: MERCHANT.mailbox,
    subject: 'Payment confirmation — £420.00 charged',
    body: `Payment confirmed. Receipt for order #1048. Amount: £420.00 GBP captured successfully.
Processor: Stripe. Card: Visa ending 4242. Customer email: daniel.okafor@example.com.`,
    receivedAt: '2026-06-10T10:15:00Z',
  },
  {
    id: 'm3',
    platform: 'Shopify',
    from: 'orders@shopify.com',
    to: MERCHANT.mailbox,
    subject: 'Order #1048 fulfilled',
    body: `Order #1048 has been fulfilled and is ready to ship. Refurbished 50mm camera lens packed.
Ship date confirmed. Customer email: daniel.okafor@example.com. Amount: £420.00.`,
    receivedAt: '2026-06-10T14:20:00Z',
  },
  {
    id: 'm4',
    platform: 'Royal Mail',
    from: 'noreply@royalmail.com',
    to: MERCHANT.mailbox,
    subject: 'Tracking created for order #1048',
    body: `A shipping label has been created. Carrier: Royal Mail. Tracking number: RN123456789GB.
Order #1048. Courier collection scheduled. Customer email: daniel.okafor@example.com.`,
    receivedAt: '2026-06-10T14:22:00Z',
  },
  {
    id: 'm5',
    platform: 'Royal Mail',
    from: 'noreply@royalmail.com',
    to: MERCHANT.mailbox,
    subject: 'Your parcel has been delivered — RN123456789GB',
    body: `Package delivered. Tracking number RN123456789GB was delivered at 11:03 on 12 June 2026
to 14 Mare Street, London, E8 3QE. Signed for. Order #1048. Carrier: Royal Mail.`,
    receivedAt: '2026-06-12T11:03:00Z',
  },
  {
    id: 'm6',
    platform: 'Customer',
    from: 'daniel.okafor@example.com',
    to: MERCHANT.mailbox,
    subject: 'Re: Order #1048',
    body: `Hi, I am writing about order #1048. The item never arrived and I did not receive my package.
I would like a full refund please. Amount £420.`,
    receivedAt: '2026-06-15T16:48:00Z',
  },
  {
    id: 'm7',
    platform: 'Stripe',
    from: 'disputes@stripe.com',
    to: MERCHANT.mailbox,
    subject: 'Stripe dispute opened on order #1048',
    body: `A Stripe dispute has been opened. Dispute reason: item not received. The cardholder did not receive item.
Order #1048. Disputed amount: £420.00 GBP. Processor: Stripe. Respond by 23 June 2026.`,
    receivedAt: '2026-06-16T09:41:00Z',
  },
]

// ── Order #1048 evidence (present items only; missing dims derived by scorer)
const ORDER_1048_EVIDENCE: EvidenceItem[] = [
  {
    id: 'e1',
    category: 'order',
    label: 'Order Proof',
    type: 'Order confirmation',
    source: 'Shopify · New order #1048',
    sourceMessageId: 'm1',
    strength: 'strong',
    summary: 'Shopify order confirmation for #1048, £420, refurbished 50mm lens.',
    relevance: 1,
  },
  {
    id: 'e2',
    category: 'payment',
    label: 'Payment Proof',
    type: 'Payment receipt',
    source: 'Stripe · Payment confirmation',
    sourceMessageId: 'm2',
    strength: 'strong',
    summary: '£420.00 captured via Stripe, Visa ending 4242.',
    relevance: 1,
  },
  {
    id: 'e3',
    category: 'product',
    label: 'Product Proof',
    type: 'Product description',
    source: 'Shopify · Order line item',
    sourceMessageId: 'm1',
    strength: 'strong',
    summary: 'Refurbished 50mm camera lens, matched to SKU and listing.',
    relevance: 1,
  },
  {
    id: 'e4',
    category: 'policy',
    label: 'Policy Proof',
    type: 'Refund policy snapshot',
    source: 'Shopify · Order confirmation footer',
    sourceMessageId: 'm1',
    strength: 'weak',
    summary: '30-day returns policy referenced but full policy snapshot not captured.',
    relevance: 0.5,
  },
  {
    id: 'e5',
    category: 'fulfilment',
    label: 'Fulfilment Proof',
    type: 'Fulfilment confirmation',
    source: 'Shopify · Order #1048 fulfilled',
    sourceMessageId: 'm3',
    strength: 'strong',
    summary: 'Order marked fulfilled and packed on 10 June.',
    relevance: 1,
  },
  {
    id: 'e6',
    category: 'delivery',
    label: 'Delivery Proof',
    type: 'Carrier delivery confirmation',
    source: 'Royal Mail · Delivered RN123456789GB',
    sourceMessageId: 'm5',
    strength: 'strong',
    summary: 'Royal Mail confirmed delivery, signed for at the order address on 12 June.',
    relevance: 1,
  },
  {
    id: 'e7',
    category: 'address',
    label: 'Address Match',
    type: 'Address verification',
    source: 'Shopify order vs Royal Mail delivery',
    sourceMessageId: 'm5',
    strength: 'strong',
    summary: 'Delivery address (14 Mare Street, E8 3QE) matches the order shipping address.',
    relevance: 1,
  },
  {
    id: 'e8',
    category: 'refund',
    label: 'Refund History',
    type: 'Refund ledger',
    source: 'Stripe · No prior refunds',
    sourceMessageId: 'm2',
    strength: 'strong',
    summary: 'No previous refunds issued on this customer or order.',
    relevance: 1,
  },
  {
    id: 'e9',
    category: 'conflict',
    label: 'Conflict Detection',
    type: 'Cross-source consistency',
    source: 'Pipeline · Cross-check',
    sourceMessageId: null,
    strength: 'strong',
    summary: 'No conflicting tracking, amount or address signals detected across sources.',
    relevance: 1,
  },
  // communication (customer_message_history) intentionally absent → scored as missing
]

const ORDER_1048_TIMELINE: TimelineEvent[] = [
  {
    id: 't1',
    timestamp: '2026-06-10T10:14:00Z',
    title: 'Order placed',
    description: 'Shopify order confirmation for #1048 (£420).',
    kind: 'order',
    sourceMessageId: 'm1',
  },
  {
    id: 't2',
    timestamp: '2026-06-10T10:15:00Z',
    title: 'Payment confirmation captured',
    description: 'Stripe captured £420.00, Visa ending 4242.',
    kind: 'payment',
    sourceMessageId: 'm2',
  },
  {
    id: 't3',
    timestamp: '2026-06-10T14:20:00Z',
    title: 'Fulfilment confirmation captured',
    description: 'Order marked fulfilled and packed.',
    kind: 'fulfilment',
    sourceMessageId: 'm3',
  },
  {
    id: 't4',
    timestamp: '2026-06-10T14:22:00Z',
    title: 'Tracking number captured',
    description: 'Royal Mail RN123456789GB created.',
    kind: 'tracking',
    sourceMessageId: 'm4',
  },
  {
    id: 't5',
    timestamp: '2026-06-12T11:03:00Z',
    title: 'Carrier marked parcel delivered',
    description: 'Royal Mail confirmed signed delivery to the order address.',
    kind: 'delivery',
    sourceMessageId: 'm5',
  },
  {
    id: 't6',
    timestamp: '2026-06-16T09:41:00Z',
    title: 'Stripe dispute detected: item_not_received',
    description: 'Cardholder opened a dispute for £420. Respond by 23 June.',
    kind: 'dispute',
    sourceMessageId: 'm7',
  },
  {
    id: 't7',
    timestamp: '2026-06-16T09:42:00Z',
    title: 'Evidence pack generated automatically',
    description: 'Score ≥ 90 triggered auto-generation of a ready-to-submit pack.',
    kind: 'pack',
    sourceMessageId: null,
  },
]

// Lightweight evidence builder for the other dashboard vaults
let evCounter = 0
function ev(
  category: EvidenceItem['category'],
  label: string,
  source: string,
  strength: EvidenceItem['strength'],
  relevance: number,
): EvidenceItem {
  evCounter += 1
  return {
    id: `ev_${category}_${evCounter}`,
    category,
    label,
    type: label,
    source,
    sourceMessageId: null,
    strength,
    summary: `${label} captured from ${source}.`,
    relevance,
  }
}

const FULL = (extra: EvidenceItem[] = []): EvidenceItem[] => [
  ev('order', 'Order Proof', 'Shopify', 'strong', 1),
  ev('payment', 'Payment Proof', 'Stripe', 'strong', 1),
  ev('product', 'Product Proof', 'Shopify', 'strong', 1),
  ev('fulfilment', 'Fulfilment Proof', 'Shopify', 'strong', 1),
  ev('address', 'Address Match', 'Carrier', 'strong', 1),
  ev('refund', 'Refund History', 'Stripe', 'strong', 1),
  ev('conflict', 'Conflict Detection', 'Pipeline', 'strong', 1),
  ...extra,
]

export const SEED_VAULTS: OrderVault[] = [
  {
    id: 'vault_1048',
    orderId: '1048',
    customer: 'Daniel Okafor',
    customerEmail: 'daniel.okafor@example.com',
    amount: 420,
    currency: 'GBP',
    product: 'Refurbished 50mm camera lens',
    fulfilmentStatus: 'delivered',
    trackingNumber: 'RN123456789GB',
    carrier: 'Royal Mail',
    evidence: ORDER_1048_EVIDENCE,
    timeline: ORDER_1048_TIMELINE,
    latestEvent: 'Stripe dispute detected · pack ready',
    latestEventAt: '2026-06-16T09:42:00Z',
    disputeStatus: 'disputed',
    disputeReason: 'item_not_received',
    disputeDeadline: '2026-06-23T23:59:00Z',
  },
  {
    id: 'vault_1042',
    orderId: '1042',
    customer: 'Priya Sharma',
    customerEmail: 'priya.sharma@example.com',
    amount: 310,
    currency: 'GBP',
    product: 'Vintage film camera body',
    fulfilmentStatus: 'delivered',
    trackingNumber: 'RN987654321GB',
    carrier: 'Royal Mail',
    evidence: FULL([
      ev('policy', 'Policy Proof', 'Shopify', 'strong', 1),
      ev('delivery', 'Delivery Proof', 'Royal Mail', 'strong', 0.9),
    ]),
    timeline: [],
    latestEvent: 'Customer reports item damaged',
    latestEventAt: '2026-06-16T08:10:00Z',
    disputeStatus: 'disputed',
    disputeReason: 'damaged_item',
    disputeDeadline: '2026-06-24T23:59:00Z',
  },
  {
    id: 'vault_1051',
    orderId: '1051',
    customer: 'Marcus Lee',
    customerEmail: 'marcus.lee@example.com',
    amount: 189,
    currency: 'GBP',
    product: 'Camera tripod kit',
    fulfilmentStatus: 'delivered',
    trackingNumber: 'RN112233445GB',
    carrier: 'Royal Mail',
    evidence: FULL([
      ev('policy', 'Policy Proof', 'Shopify', 'strong', 1),
      ev('delivery', 'Delivery Proof', 'Royal Mail', 'strong', 1),
    ]),
    timeline: [],
    latestEvent: 'Refund request received',
    latestEventAt: '2026-06-16T07:30:00Z',
    disputeStatus: 'signal',
    disputeReason: 'refund_request',
    disputeDeadline: '2026-06-25T23:59:00Z',
  },
  {
    id: 'vault_1039',
    orderId: '1039',
    customer: 'Aisha Rahman',
    customerEmail: 'aisha.rahman@example.com',
    amount: 540,
    currency: 'GBP',
    product: 'Mirrorless camera kit',
    fulfilmentStatus: 'in_transit',
    trackingNumber: 'RN556677889GB',
    carrier: 'Royal Mail',
    // delivery proof missing
    evidence: FULL([ev('policy', 'Policy Proof', 'Shopify', 'strong', 1)]),
    timeline: [],
    latestEvent: 'In transit · awaiting delivery scan',
    latestEventAt: '2026-06-15T18:02:00Z',
    disputeStatus: 'none',
  },
  {
    id: 'vault_1055',
    orderId: '1055',
    customer: 'Tom Hughes',
    customerEmail: 'tom.hughes@example.com',
    amount: 95,
    currency: 'GBP',
    product: 'Lens cleaning kit',
    fulfilmentStatus: 'delivered',
    trackingNumber: 'RN221144556GB',
    carrier: 'Royal Mail',
    evidence: FULL([
      ev('policy', 'Policy Proof', 'Shopify', 'strong', 1),
      ev('delivery', 'Delivery Proof', 'Royal Mail', 'strong', 1),
    ]),
    timeline: [],
    latestEvent: 'Delivered · dispute-ready',
    latestEventAt: '2026-06-14T12:20:00Z',
    disputeStatus: 'none',
  },
  {
    id: 'vault_1060',
    orderId: '1060',
    customer: 'Sofia Romano',
    customerEmail: 'sofia.romano@example.com',
    amount: 275,
    currency: 'GBP',
    product: 'Prime lens 35mm',
    fulfilmentStatus: 'delivered',
    trackingNumber: 'RN334455667GB',
    carrier: 'Royal Mail',
    // policy proof missing
    evidence: FULL([ev('delivery', 'Delivery Proof', 'Royal Mail', 'strong', 1)]),
    timeline: [],
    latestEvent: 'Delivered · missing policy snapshot',
    latestEventAt: '2026-06-13T15:45:00Z',
    disputeStatus: 'none',
  },
  {
    id: 'vault_1033',
    orderId: '1033',
    customer: 'Leah Cohen',
    customerEmail: 'leah.cohen@example.com',
    amount: 130,
    currency: 'GBP',
    product: 'Camera strap & case',
    fulfilmentStatus: 'delivered',
    trackingNumber: 'RN778899001GB',
    carrier: 'Royal Mail',
    evidence: FULL([
      ev('policy', 'Policy Proof', 'Shopify', 'strong', 1),
      ev('delivery', 'Delivery Proof', 'Royal Mail', 'strong', 1),
    ]),
    timeline: [],
    latestEvent: 'Delivered · dispute-ready',
    latestEventAt: '2026-06-11T09:05:00Z',
    disputeStatus: 'none',
  },
]

export const SEED_DIGEST: DigestStats = {
  scanned: 184,
  relevant: 39,
  vaultsCreated: 12,
  updated: 9,
  deliveryConfirmations: 7,
  disputeReady: 11,
  newSignals: 3,
  readyPacks: 2,
  disputedValue: 730,
  recoverableValue: 620,
}

export function getVaultById(id: string): OrderVault | undefined {
  return SEED_VAULTS.find((v) => v.orderId === id || v.id === id)
}
